language: java
jdk:
  - oraclejdk8
os:
  - linux
sudo: required
services:
  - docker
notifications:
  on_success:
    - change
  on_failure:
    - change
cache:
  directories:
    - .autoconf
    - $HOME/.m2
addons:
  apt:
    packages:
      - graphviz
script:
  - mvn clean package
before_deploy:
  - git fetch --tags
after_success:
  - docker version  
  # Build Docker image
  - docker build -t sualeh/schemacrawler-webapp .
  - docker tag sualeh/schemacrawler-webapp sualeh/schemacrawler-webapp:v14.17.04.04
  - docker tag sualeh/schemacrawler-webapp sualeh/schemacrawler-webapp:latest
  # Deploy image to Docker Hub
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push sualeh/schemacrawler-webapp
  - docker logout  
  # Deploy image to Heroku
  - docker tag sualeh/schemacrawler-webapp registry.heroku.com/schemacrawler-webapp/web
  - docker login --username=_ --password=ae3b3e29-2993-412f-8281-c3744046d729 registry.heroku.com
  - docker push registry.heroku.com/schemacrawler-webapp/web
  - docker logout registry.heroku.com
  # Remove the image, so Travis does not cache it
  - docker rm sualeh/schemacrawler-webapp
