dist: trusty
language: java
jdk:
- oraclejdk8
os:
- linux
sudo: required
services:
- docker
notifications:
  on_success:
  - change
  on_failure:
  - change
cache:
  directories:
  - .autoconf
  - $HOME/.m2
addons:
  apt:
    packages:
    - graphviz
script:
- mvn clean package jacoco:report coveralls:report
before_deploy:
- git fetch --tags
after_success:
- docker version
- docker build -t schemacrawler/schemacrawler-webapp .
- docker tag schemacrawler/schemacrawler-webapp schemacrawler/schemacrawler-webapp:v16.5.2.1
- docker tag schemacrawler/schemacrawler-webapp schemacrawler/schemacrawler-webapp:latest
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- docker push schemacrawler/schemacrawler-webapp
- docker logout
- docker rm schemacrawler/schemacrawler-webapp
deploy:
  - provider: heroku
    api_key:
      secure: LQmIAdRml8eZwuz36jv5xZVQhkZiIF6gN+0Yq538cMjz4598EEGyd0/LsBQJchO0PkDLDPdYXaO/WIIe1s3DARe+9XxNqeNo2Hv3cgzQw/znSyphhXpfDkIS0LW27NijJRLo7htZXuRHKPcKtGWZdRin5eHFYya7n4EuvhyH8G5C5aKeUmey+pURpYwx/vXE/+xKfNkEOQFpTb3roxCEH3f/QULStZPNbRKBY5rgy4T6k7L2mOI05h2yJD6IlObwRcateILU1/7CP24zLg8m6Fadnke4TKVpmQMZ4WN+/7h2BdfOo1S2gfq8uu0C+pf/2VKdDXSu5D42kAMzIMMTbJNLitD7Q/bvK41GWPegtZj2XX/pOk9NfWc45EJQ0td7rohb7VdJDkaSbGNu7dkIIT3l1fFyJWmKys2jKRoNeFJR5+q9CvFaZhKMTPk9kvs7E0AOi4W4H1MbAJeDgHuv83W4M9dB5Ekp58R1mCMbpHviMhAJYRq6zBhCRFhopgnr4JZAkeR6fXCqlcVFh3c4QuuGwbbTaMWIQOw9tIeKLeTb0ppjpRM+3uBmpZygydRQLRnirEXDLKVsz1MOPUBh4YWDpHL27Aw+oHDDJWo8YkC3XmZ9mAOOPjI8J0y7NpL8iv/UPGMK/hoDQj1rE0CMUbX4XhHeHc662D1T9mOCHUc=
    app: schemacrawler-webapp
    skip_cleanup: true
    on:
      repo: schemacrawler/SchemaCrawler-Web-Application
      branch: master
      tags: true
