name: Create Release

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - '*'
    tags:
      - v[0-9]+.[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+.[0-9]+-[A-Z]

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:

# SETUP BUILD ENVIRONMENT
    - id: cache-m2
      name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - id: cache-ivy2
      name: Cache Ivy packages
      uses: actions/cache@v2
      with:
        path: ~/.ivy2
        key: ${{ runner.os }}-ivy2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-ivy2
    - id: checkout-code
      name: Checkout code
      uses: actions/checkout@v2
    - id: setup-jdk
      name: Setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: 8
        server-id: sonatype-nexus
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    - id: install-packages
      name: Install packages
      run: |
        # Install Graphviz
        sudo apt-get -qq update
        sudo apt-get -q install graphviz
    - id: show-environment
      name: Show environment
      run: |
        # Show environment
        echo github.repository: ${{ github.repository }}
        echo github.ref: ${{ github.head_ref || github.ref }}
        echo github.sha: ${{ github.sha }}
        mvn -v
        cat ~/.m2/settings.xml

# BUILD FOR DISTRIBUTION
    - id: build
      name: Build and test for distribution
      run: |
        # Build
        mvn \
          --no-transfer-progress \
          --batch-mode \
          -Ddocker.skip=false \
          clean install

# PUBLISH DOCKER IMAGE
    - id: publish-docker-image
      name: Publish Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        # Publish Docker image
        docker version
        docker tag schemacrawler/schemacrawler-webapp schemacrawler/schemacrawler-webapp:v16.11.7.4
        docker tag schemacrawler/schemacrawler-webapp schemacrawler/schemacrawler-webapp:latest
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker push schemacrawler/schemacrawler-webapp
        docker logout

# DEPLOY TO HEROKU
    - name: Deploy to Heroku
      id: deploy-to-heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: schemacrawler-webapp
      run: |
        heroku container:login
        echo "$(heroku auth:token)" | docker login --username=_ --password-stdin registry.heroku.com
        docker tag schemacrawler/schemacrawler-webapp registry.heroku.com/${{ env.HEROKU_APP_NAME }}/web
        docker push registry.heroku.com/${{ env.HEROKU_APP_NAME }}/web
        docker logout

# CREATE GITHUB RELEASE AND ADD ASSETS
    - id: create-release
      name: Create GitHub release
      uses: actions/create-release@latest
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body: |
          SchemaCrawler Webapp Release ${{ github.sha }}
        draft: false
        prerelease: false
    - id: upload-release-zip
      name: Upload SchemaCrawler Webapp distribution
      uses: actions/upload-release-asset@latest
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ./target/schemacrawler-webapp-16.11.7.4.jar
        asset_name: schemacrawler-webapp-16.11.7.4.jar
        asset_content_type: application/zip
